site_name: Camill Kaipf
site_url: https://ckaipf.github.io

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: purple
  features:
  - navigation.indexes
  favicon: assets/1F52E_color.png
  logo: assets/1F52E_color.png
  font:
    text: Source Code Pro

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
