site_name: Camill Kaipf
site_url: https://ckaipf.github.io

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: purple
  features:
  - navigation.indexes
  - navigation.footer
  - navigation.tabs
  icon:
    logo: material/crystal-ball
  font:
    text: Source Code Pro

nav:
  - About me: 'index.md'
  - Kubernetes helpers: 
      - Helpers with fzf: 'kubernetes-helpers/kubernetes-helpers.md'
      - Sniff Kubernetes pods: 'kubernetes-helpers/sniff-kubernetes-pods.md'
  - Istio:
      - Enable monitoring of passthrough traffic: 'istio/enable-passthrough-monitoring.md'
  - Legal Notice: 'legal-notice.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ckaipf
  # consent:
  #     title: Cookie consent
  #     description: >- 
  #       We use cookies to recognize your repeated visits and preferences, as well
  #       as to measure the effectiveness of our documentation and whether users
  #       find what they're searching for. With your consent, you're helping us to
  #       make our documentation better.


copyright: >
  Copyright &copy; 2024 - 2024 Camill Kaipf

plugins:
  - privacy